---
title: "Wyniki metamodeli"
author: "Hubert Baniecki, Łukasz Brzozowski"
date: "27.03.2019"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    code_folding: hide
    number_sections: true
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(reshape)
dat <- read.csv("./wynikiModeli.csv", sep=",")
dat2 <- read.csv("./dataset.csv", sep = ",")
#dat2 <- dat2 %>% select(-c(1, 2, performance2))
```

# Prezentacja danych

- Dane dotyczą modeli klasyfikacyjnych

- Przewidujemy wynik `accuracy`

```{r}
dat2
```

- Połączyliśmy modele, z których korzystano najrzadziej, w jedną klasę
```{r}
temp <- as.data.frame(table(dat2$modelName))
temp[order(-temp$Freq),]
```


# Wyniki

## Miary jakości modeli

```{r warning=FALSE, message=FALSE, error=FALSE}
temp <- select(dat, X, Rsquared, RMSE, MAE)
temp <- melt(temp)
ggplot(data = temp, aes(x = X, y = value, fill = variable)) +
  geom_bar(stat = "identity", position=position_dodge()) +xlab("")
```

## Feature importance

```{r cache=TRUE, warning=FALSE, message=FALSE, error=FALSE}
set.seed(111)
df1 <- dat2
train_set1 <- sample_frac(df1, 0.75)
test_set1 <- setdiff(df1, train_set1)

regr_rf1 <- caret::train(performance1~., data = train_set1, method = "rf", ntree = 100)

library(DALEX)
library(ingredients)
explainer_rf1 <- explain(regr_rf1, data = select(test_set1, -performance1), y = test_set1$performance1, label = "rf")
fi_rf2 <- feature_importance(explainer_rf1, loss_function = loss_root_mean_square)
plot(fi_rf2)
```
